### ISSUE TITLE
style and position

### ISSUE THREAD

**Issue by niconacre** [WebCrew/humhub-adspanel#6]
Hi,
can you indicate me how to apply a clear style, instead of the dark one ;)
and also how to change the panel position (I'd like to move it below recent activities)
thx for all !

**Comment by WebCrew** [comment]
Because of the position - I have integrated the option to setup the position - there is the **Adspanel Setting** link at HumHubs admin backend. You can choose a position from 1- 99999999 - just play around with the number until you are satisfied with the position. 

Because of the style You have to play around with the CSS. The module uses the default style of the HumHub theme which you are using.

**Comment by niconacre** [comment]
yes, thanks, I didn't notice it sorry !

**Comment by WebCrew** [comment]
@niconacre its ok no problem :) I always try to help 

I wish you a lot of success and fun with HumHub
